# Permalinks
permalink:            pretty

# reveal options
reveal:
  slide_separator:    "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator:    "<p>Notes:</p>"
  title_slide:        true

# Setup
title:                MTEC1003-slides
tagline:              "Slides for Prof. Goldford's MTEC1003 Fall 2020"
description:          "A template for creating slide decks using Markdown and <a href='//jekyllrb.com'>Jekyll</a>, using <a href='//github.com/poole/lanyon'>Lanyon</a> by <a href='//twitter.com/mdo'>@mdo</a>."
url:                  http://einbahnstrasse.github.io/MTEC1003-slides
baseurl:              /MTEC1003-slides
markdown:             kramdown
kramdown:
  input:              GFM

collections:
  slides:
    output:           true
    permalink:        /:collection/:title/

# # About/contact
# author:
#   name:               Adam Hollett
#   url:                https://twitter.com/admhlt
#   email:              mail@adamhollett.com

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides
